name: Run Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-api:
    name: Check API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/api
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: |
            apps/api/requirements.txt
            apps/api/requirements-dev.txt

      - name: Install xmlsec dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libxml2-dev libxmlsec1-dev libxmlsec1-openssl
          version: 1.0

      - name: Install Python dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Format with Black
        uses: reviewdog/action-black@v3
        with:
          workdir: apps/api
          level: warning
          reporter: github-pr-review
          filter_mode: file

      - name: Lint with flake8
        uses: reviewdog/action-flake8@v3
        with:
          workdir: apps/api
          level: warning
          reporter: github-pr-review
          filter_mode: nofilter

      - name: Cache `.mypy_cache`
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.mypy_cache
          key: ${{ runner.os }}-python3.9-mypy-cache

      - name: Lint with mypy (review)
        uses: tsuyoshicho/action-mypy@v5
        if: github.event_name == 'pull_request'
        with:
          workdir: apps/api
          level: error
          reporter: github-pr-review
          filter_mode: nofilter

      - name: Run mypy (check)
        uses: tsuyoshicho/action-mypy@v4
        if: github.event_name == 'push'
        with:
          workdir: apps/api
          level: error
          reporter: github-check

      - name: Run tests with pytest
        run: pytest
        # uses: reviewdog/action-pytest@v1 (WIP)
        # with:
        #   reporter: github-pr-review
        #   level: error

  check-frontend:
    name: Check Site
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        # pnpm version will be determined by `packageManager` in `package.json`

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install frontend dependencies
        run: pnpm install

      - name: Format with Prettier
        uses: EPMatt/reviewdog-action-prettier@v1
        with:
          level: warning
          reporter: github-pr-review
          filter_mode: file
          prettier_flags: apps/site/src

      - name: Lint with ESLint (review)
        uses: reviewdog/action-eslint@v1
        if: github.event_name == 'pull_request'
        with:
          level: error
          reporter: github-pr-review
          filter_mode: nofilter
          eslint_flags: apps/site/src

      - name: Lint with ESLint (check)
        uses: reviewdog/action-eslint@v1
        if: github.event_name == 'push'
        with:
          workDir: apps/site
          level: error
          reporter: github-check
          eslint_flags: src
